[package]
org = "wso2"
name = "catalog_navigation_workflow"
version = "0.1.0"
distribution = "2201.10.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "sap.commerce"
version = "0.1.0"
repository = "local"
