[package]
org = "wso2"
name = "sheet_collaboration_setup"
version = "0.1.0"
distribution = "2201.10.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "smartsheet"
version = "0.1.0"
repository = "local"
